/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ModeratorRouteImport } from './routes/_moderator'
import { Route as LabelRouteImport } from './routes/_label'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ArtistRouteImport } from './routes/_artist'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as LabelLabelIndexRouteImport } from './routes/_label/label/index'
import { Route as ArtistArtistIndexRouteImport } from './routes/_artist/artist/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ModeratorModerationReleaseIdRouteImport } from './routes/_moderator/moderation/$releaseId'
import { Route as LabelLabelProfileRouteImport } from './routes/_label/label/profile'
import { Route as ArtistArtistProfileRouteImport } from './routes/_artist/artist/profile'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin/reports'
import { Route as AdminAdminPlatformsRouteImport } from './routes/_admin/admin/platforms'
import { Route as LabelLabelRoyaltiesIndexRouteImport } from './routes/_label/label/royalties/index'
import { Route as ArtistArtistRoyaltiesIndexRouteImport } from './routes/_artist/artist/royalties/index'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as LabelLabelRoyaltiesReportIdRouteImport } from './routes/_label/label/royalties/$reportId'
import { Route as ArtistArtistRoyaltiesReportIdRouteImport } from './routes/_artist/artist/royalties/$reportId'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users/$userId'
import { Route as LabelLabelReleasesReleaseIdIndexRouteImport } from './routes/_label/label/releases/$releaseId/index'
import { Route as ArtistArtistReleasesReleaseIdIndexRouteImport } from './routes/_artist/artist/releases/$releaseId/index'

const ModeratorModerationIndexLazyRouteImport = createFileRoute(
  '/_moderator/moderation/',
)()
const LabelLabelReleasesIndexLazyRouteImport = createFileRoute(
  '/_label/label/releases/',
)()
const ArtistArtistReleasesIndexLazyRouteImport = createFileRoute(
  '/_artist/artist/releases/',
)()
const LabelLabelReleasesNewIndexLazyRouteImport = createFileRoute(
  '/_label/label/releases/new/',
)()
const ArtistArtistReleasesNewIndexLazyRouteImport = createFileRoute(
  '/_artist/artist/releases/new/',
)()

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/_moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/_label',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRoute = ArtistRouteImport.update({
  id: '/_artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ModeratorModerationIndexLazyRoute =
  ModeratorModerationIndexLazyRouteImport.update({
    id: '/moderation/',
    path: '/moderation/',
    getParentRoute: () => ModeratorRoute,
  } as any).lazy(() =>
    import('./routes/_moderator/moderation/index.lazy').then((d) => d.Route),
  )
const LabelLabelIndexRoute = LabelLabelIndexRouteImport.update({
  id: '/label/',
  path: '/label/',
  getParentRoute: () => LabelRoute,
} as any)
const ArtistArtistIndexRoute = ArtistArtistIndexRouteImport.update({
  id: '/artist/',
  path: '/artist/',
  getParentRoute: () => ArtistRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ModeratorModerationReleaseIdRoute =
  ModeratorModerationReleaseIdRouteImport.update({
    id: '/moderation/$releaseId',
    path: '/moderation/$releaseId',
    getParentRoute: () => ModeratorRoute,
  } as any)
const LabelLabelProfileRoute = LabelLabelProfileRouteImport.update({
  id: '/label/profile',
  path: '/label/profile',
  getParentRoute: () => LabelRoute,
} as any)
const ArtistArtistProfileRoute = ArtistArtistProfileRouteImport.update({
  id: '/artist/profile',
  path: '/artist/profile',
  getParentRoute: () => ArtistRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlatformsRoute = AdminAdminPlatformsRouteImport.update({
  id: '/admin/platforms',
  path: '/admin/platforms',
  getParentRoute: () => AdminRoute,
} as any)
const LabelLabelReleasesIndexLazyRoute =
  LabelLabelReleasesIndexLazyRouteImport.update({
    id: '/label/releases/',
    path: '/label/releases/',
    getParentRoute: () => LabelRoute,
  } as any).lazy(() =>
    import('./routes/_label/label/releases/index.lazy').then((d) => d.Route),
  )
const ArtistArtistReleasesIndexLazyRoute =
  ArtistArtistReleasesIndexLazyRouteImport.update({
    id: '/artist/releases/',
    path: '/artist/releases/',
    getParentRoute: () => ArtistRoute,
  } as any).lazy(() =>
    import('./routes/_artist/artist/releases/index.lazy').then((d) => d.Route),
  )
const LabelLabelRoyaltiesIndexRoute =
  LabelLabelRoyaltiesIndexRouteImport.update({
    id: '/label/royalties/',
    path: '/label/royalties/',
    getParentRoute: () => LabelRoute,
  } as any)
const ArtistArtistRoyaltiesIndexRoute =
  ArtistArtistRoyaltiesIndexRouteImport.update({
    id: '/artist/royalties/',
    path: '/artist/royalties/',
    getParentRoute: () => ArtistRoute,
  } as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const LabelLabelRoyaltiesReportIdRoute =
  LabelLabelRoyaltiesReportIdRouteImport.update({
    id: '/label/royalties/$reportId',
    path: '/label/royalties/$reportId',
    getParentRoute: () => LabelRoute,
  } as any)
const ArtistArtistRoyaltiesReportIdRoute =
  ArtistArtistRoyaltiesReportIdRouteImport.update({
    id: '/artist/royalties/$reportId',
    path: '/artist/royalties/$reportId',
    getParentRoute: () => ArtistRoute,
  } as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const LabelLabelReleasesNewIndexLazyRoute =
  LabelLabelReleasesNewIndexLazyRouteImport.update({
    id: '/label/releases/new/',
    path: '/label/releases/new/',
    getParentRoute: () => LabelRoute,
  } as any).lazy(() =>
    import('./routes/_label/label/releases/new/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ArtistArtistReleasesNewIndexLazyRoute =
  ArtistArtistReleasesNewIndexLazyRouteImport.update({
    id: '/artist/releases/new/',
    path: '/artist/releases/new/',
    getParentRoute: () => ArtistRoute,
  } as any).lazy(() =>
    import('./routes/_artist/artist/releases/new/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LabelLabelReleasesReleaseIdIndexRoute =
  LabelLabelReleasesReleaseIdIndexRouteImport.update({
    id: '/label/releases/$releaseId/',
    path: '/label/releases/$releaseId/',
    getParentRoute: () => LabelRoute,
  } as any).lazy(() =>
    import('./routes/_label/label/releases/$releaseId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ArtistArtistReleasesReleaseIdIndexRoute =
  ArtistArtistReleasesReleaseIdIndexRouteImport.update({
    id: '/artist/releases/$releaseId/',
    path: '/artist/releases/$releaseId/',
    getParentRoute: () => ArtistRoute,
  } as any).lazy(() =>
    import('./routes/_artist/artist/releases/$releaseId/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/platforms': typeof AdminAdminPlatformsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/artist/profile': typeof ArtistArtistProfileRoute
  '/label/profile': typeof LabelLabelProfileRoute
  '/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/artist': typeof ArtistArtistIndexRoute
  '/label': typeof LabelLabelIndexRoute
  '/moderation': typeof ModeratorModerationIndexLazyRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/artist/royalties/$reportId': typeof ArtistArtistRoyaltiesReportIdRoute
  '/label/royalties/$reportId': typeof LabelLabelRoyaltiesReportIdRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/artist/royalties': typeof ArtistArtistRoyaltiesIndexRoute
  '/label/royalties': typeof LabelLabelRoyaltiesIndexRoute
  '/artist/releases': typeof ArtistArtistReleasesIndexLazyRoute
  '/label/releases': typeof LabelLabelReleasesIndexLazyRoute
  '/artist/releases/$releaseId': typeof ArtistArtistReleasesReleaseIdIndexRoute
  '/label/releases/$releaseId': typeof LabelLabelReleasesReleaseIdIndexRoute
  '/artist/releases/new': typeof ArtistArtistReleasesNewIndexLazyRoute
  '/label/releases/new': typeof LabelLabelReleasesNewIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/platforms': typeof AdminAdminPlatformsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/artist/profile': typeof ArtistArtistProfileRoute
  '/label/profile': typeof LabelLabelProfileRoute
  '/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/artist': typeof ArtistArtistIndexRoute
  '/label': typeof LabelLabelIndexRoute
  '/moderation': typeof ModeratorModerationIndexLazyRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/artist/royalties/$reportId': typeof ArtistArtistRoyaltiesReportIdRoute
  '/label/royalties/$reportId': typeof LabelLabelRoyaltiesReportIdRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/artist/royalties': typeof ArtistArtistRoyaltiesIndexRoute
  '/label/royalties': typeof LabelLabelRoyaltiesIndexRoute
  '/artist/releases': typeof ArtistArtistReleasesIndexLazyRoute
  '/label/releases': typeof LabelLabelReleasesIndexLazyRoute
  '/artist/releases/$releaseId': typeof ArtistArtistReleasesReleaseIdIndexRoute
  '/label/releases/$releaseId': typeof LabelLabelReleasesReleaseIdIndexRoute
  '/artist/releases/new': typeof ArtistArtistReleasesNewIndexLazyRoute
  '/label/releases/new': typeof LabelLabelReleasesNewIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_artist': typeof ArtistRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_label': typeof LabelRouteWithChildren
  '/_moderator': typeof ModeratorRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_admin/admin/platforms': typeof AdminAdminPlatformsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_artist/artist/profile': typeof ArtistArtistProfileRoute
  '/_label/label/profile': typeof LabelLabelProfileRoute
  '/_moderator/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_artist/artist/': typeof ArtistArtistIndexRoute
  '/_label/label/': typeof LabelLabelIndexRoute
  '/_moderator/moderation/': typeof ModeratorModerationIndexLazyRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_artist/artist/royalties/$reportId': typeof ArtistArtistRoyaltiesReportIdRoute
  '/_label/label/royalties/$reportId': typeof LabelLabelRoyaltiesReportIdRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_artist/artist/royalties/': typeof ArtistArtistRoyaltiesIndexRoute
  '/_label/label/royalties/': typeof LabelLabelRoyaltiesIndexRoute
  '/_artist/artist/releases/': typeof ArtistArtistReleasesIndexLazyRoute
  '/_label/label/releases/': typeof LabelLabelReleasesIndexLazyRoute
  '/_artist/artist/releases/$releaseId/': typeof ArtistArtistReleasesReleaseIdIndexRoute
  '/_label/label/releases/$releaseId/': typeof LabelLabelReleasesReleaseIdIndexRoute
  '/_artist/artist/releases/new/': typeof ArtistArtistReleasesNewIndexLazyRoute
  '/_label/label/releases/new/': typeof LabelLabelReleasesNewIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/platforms'
    | '/admin/reports'
    | '/artist/profile'
    | '/label/profile'
    | '/moderation/$releaseId'
    | '/admin'
    | '/artist'
    | '/label'
    | '/moderation'
    | '/admin/users/$userId'
    | '/artist/royalties/$reportId'
    | '/label/royalties/$reportId'
    | '/admin/users'
    | '/artist/royalties'
    | '/label/royalties'
    | '/artist/releases'
    | '/label/releases'
    | '/artist/releases/$releaseId'
    | '/label/releases/$releaseId'
    | '/artist/releases/new'
    | '/label/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/platforms'
    | '/admin/reports'
    | '/artist/profile'
    | '/label/profile'
    | '/moderation/$releaseId'
    | '/admin'
    | '/artist'
    | '/label'
    | '/moderation'
    | '/admin/users/$userId'
    | '/artist/royalties/$reportId'
    | '/label/royalties/$reportId'
    | '/admin/users'
    | '/artist/royalties'
    | '/label/royalties'
    | '/artist/releases'
    | '/label/releases'
    | '/artist/releases/$releaseId'
    | '/label/releases/$releaseId'
    | '/artist/releases/new'
    | '/label/releases/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_artist'
    | '/_auth'
    | '/_label'
    | '/_moderator'
    | '/unauthorized'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_admin/admin/platforms'
    | '/_admin/admin/reports'
    | '/_artist/artist/profile'
    | '/_label/label/profile'
    | '/_moderator/moderation/$releaseId'
    | '/_admin/admin/'
    | '/_artist/artist/'
    | '/_label/label/'
    | '/_moderator/moderation/'
    | '/_admin/admin/users/$userId'
    | '/_artist/artist/royalties/$reportId'
    | '/_label/label/royalties/$reportId'
    | '/_admin/admin/users/'
    | '/_artist/artist/royalties/'
    | '/_label/label/royalties/'
    | '/_artist/artist/releases/'
    | '/_label/label/releases/'
    | '/_artist/artist/releases/$releaseId/'
    | '/_label/label/releases/$releaseId/'
    | '/_artist/artist/releases/new/'
    | '/_label/label/releases/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistRoute: typeof ArtistRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LabelRoute: typeof LabelRouteWithChildren
  ModeratorRoute: typeof ModeratorRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_moderator': {
      id: '/_moderator'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_label': {
      id: '/_label'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_artist': {
      id: '/_artist'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_moderator/moderation/': {
      id: '/_moderator/moderation/'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModeratorModerationIndexLazyRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_label/label/': {
      id: '/_label/label/'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelLabelIndexRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/': {
      id: '/_artist/artist/'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistArtistIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_moderator/moderation/$releaseId': {
      id: '/_moderator/moderation/$releaseId'
      path: '/moderation/$releaseId'
      fullPath: '/moderation/$releaseId'
      preLoaderRoute: typeof ModeratorModerationReleaseIdRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_label/label/profile': {
      id: '/_label/label/profile'
      path: '/label/profile'
      fullPath: '/label/profile'
      preLoaderRoute: typeof LabelLabelProfileRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/profile': {
      id: '/_artist/artist/profile'
      path: '/artist/profile'
      fullPath: '/artist/profile'
      preLoaderRoute: typeof ArtistArtistProfileRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/platforms': {
      id: '/_admin/admin/platforms'
      path: '/admin/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminAdminPlatformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_label/label/releases/': {
      id: '/_label/label/releases/'
      path: '/label/releases'
      fullPath: '/label/releases'
      preLoaderRoute: typeof LabelLabelReleasesIndexLazyRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/releases/': {
      id: '/_artist/artist/releases/'
      path: '/artist/releases'
      fullPath: '/artist/releases'
      preLoaderRoute: typeof ArtistArtistReleasesIndexLazyRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_label/label/royalties/': {
      id: '/_label/label/royalties/'
      path: '/label/royalties'
      fullPath: '/label/royalties'
      preLoaderRoute: typeof LabelLabelRoyaltiesIndexRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/royalties/': {
      id: '/_artist/artist/royalties/'
      path: '/artist/royalties'
      fullPath: '/artist/royalties'
      preLoaderRoute: typeof ArtistArtistRoyaltiesIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_label/label/royalties/$reportId': {
      id: '/_label/label/royalties/$reportId'
      path: '/label/royalties/$reportId'
      fullPath: '/label/royalties/$reportId'
      preLoaderRoute: typeof LabelLabelRoyaltiesReportIdRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/royalties/$reportId': {
      id: '/_artist/artist/royalties/$reportId'
      path: '/artist/royalties/$reportId'
      fullPath: '/artist/royalties/$reportId'
      preLoaderRoute: typeof ArtistArtistRoyaltiesReportIdRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_label/label/releases/new/': {
      id: '/_label/label/releases/new/'
      path: '/label/releases/new'
      fullPath: '/label/releases/new'
      preLoaderRoute: typeof LabelLabelReleasesNewIndexLazyRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/releases/new/': {
      id: '/_artist/artist/releases/new/'
      path: '/artist/releases/new'
      fullPath: '/artist/releases/new'
      preLoaderRoute: typeof ArtistArtistReleasesNewIndexLazyRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/_label/label/releases/$releaseId/': {
      id: '/_label/label/releases/$releaseId/'
      path: '/label/releases/$releaseId'
      fullPath: '/label/releases/$releaseId'
      preLoaderRoute: typeof LabelLabelReleasesReleaseIdIndexRouteImport
      parentRoute: typeof LabelRoute
    }
    '/_artist/artist/releases/$releaseId/': {
      id: '/_artist/artist/releases/$releaseId/'
      path: '/artist/releases/$releaseId'
      fullPath: '/artist/releases/$releaseId'
      preLoaderRoute: typeof ArtistArtistReleasesReleaseIdIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminPlatformsRoute: typeof AdminAdminPlatformsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminPlatformsRoute: AdminAdminPlatformsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtistRouteChildren {
  ArtistArtistProfileRoute: typeof ArtistArtistProfileRoute
  ArtistArtistIndexRoute: typeof ArtistArtistIndexRoute
  ArtistArtistRoyaltiesReportIdRoute: typeof ArtistArtistRoyaltiesReportIdRoute
  ArtistArtistRoyaltiesIndexRoute: typeof ArtistArtistRoyaltiesIndexRoute
  ArtistArtistReleasesIndexLazyRoute: typeof ArtistArtistReleasesIndexLazyRoute
  ArtistArtistReleasesReleaseIdIndexRoute: typeof ArtistArtistReleasesReleaseIdIndexRoute
  ArtistArtistReleasesNewIndexLazyRoute: typeof ArtistArtistReleasesNewIndexLazyRoute
}

const ArtistRouteChildren: ArtistRouteChildren = {
  ArtistArtistProfileRoute: ArtistArtistProfileRoute,
  ArtistArtistIndexRoute: ArtistArtistIndexRoute,
  ArtistArtistRoyaltiesReportIdRoute: ArtistArtistRoyaltiesReportIdRoute,
  ArtistArtistRoyaltiesIndexRoute: ArtistArtistRoyaltiesIndexRoute,
  ArtistArtistReleasesIndexLazyRoute: ArtistArtistReleasesIndexLazyRoute,
  ArtistArtistReleasesReleaseIdIndexRoute:
    ArtistArtistReleasesReleaseIdIndexRoute,
  ArtistArtistReleasesNewIndexLazyRoute: ArtistArtistReleasesNewIndexLazyRoute,
}

const ArtistRouteWithChildren =
  ArtistRoute._addFileChildren(ArtistRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LabelRouteChildren {
  LabelLabelProfileRoute: typeof LabelLabelProfileRoute
  LabelLabelIndexRoute: typeof LabelLabelIndexRoute
  LabelLabelRoyaltiesReportIdRoute: typeof LabelLabelRoyaltiesReportIdRoute
  LabelLabelRoyaltiesIndexRoute: typeof LabelLabelRoyaltiesIndexRoute
  LabelLabelReleasesIndexLazyRoute: typeof LabelLabelReleasesIndexLazyRoute
  LabelLabelReleasesReleaseIdIndexRoute: typeof LabelLabelReleasesReleaseIdIndexRoute
  LabelLabelReleasesNewIndexLazyRoute: typeof LabelLabelReleasesNewIndexLazyRoute
}

const LabelRouteChildren: LabelRouteChildren = {
  LabelLabelProfileRoute: LabelLabelProfileRoute,
  LabelLabelIndexRoute: LabelLabelIndexRoute,
  LabelLabelRoyaltiesReportIdRoute: LabelLabelRoyaltiesReportIdRoute,
  LabelLabelRoyaltiesIndexRoute: LabelLabelRoyaltiesIndexRoute,
  LabelLabelReleasesIndexLazyRoute: LabelLabelReleasesIndexLazyRoute,
  LabelLabelReleasesReleaseIdIndexRoute: LabelLabelReleasesReleaseIdIndexRoute,
  LabelLabelReleasesNewIndexLazyRoute: LabelLabelReleasesNewIndexLazyRoute,
}

const LabelRouteWithChildren = LabelRoute._addFileChildren(LabelRouteChildren)

interface ModeratorRouteChildren {
  ModeratorModerationReleaseIdRoute: typeof ModeratorModerationReleaseIdRoute
  ModeratorModerationIndexLazyRoute: typeof ModeratorModerationIndexLazyRoute
}

const ModeratorRouteChildren: ModeratorRouteChildren = {
  ModeratorModerationReleaseIdRoute: ModeratorModerationReleaseIdRoute,
  ModeratorModerationIndexLazyRoute: ModeratorModerationIndexLazyRoute,
}

const ModeratorRouteWithChildren = ModeratorRoute._addFileChildren(
  ModeratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistRoute: ArtistRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LabelRoute: LabelRouteWithChildren,
  ModeratorRoute: ModeratorRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
