/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UserRouteImport } from './routes/_user'
import { Route as ModeratorRouteImport } from './routes/_moderator'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as UserRoyaltiesIndexRouteImport } from './routes/_user/royalties/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as UserRoyaltiesReportIdRouteImport } from './routes/_user/royalties/$reportId'
import { Route as ModeratorModerationReleaseIdRouteImport } from './routes/_moderator/moderation/$releaseId'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin/reports'
import { Route as AdminAdminPlatformsRouteImport } from './routes/_admin/admin/platforms'
import { Route as UserReleasesReleaseIdIndexRouteImport } from './routes/_user/releases/$releaseId/index'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users/$userId'

const UserReleasesIndexLazyRouteImport = createFileRoute('/_user/releases/')()
const ModeratorModerationIndexLazyRouteImport = createFileRoute(
  '/_moderator/moderation/',
)()
const UserReleasesNewIndexLazyRouteImport = createFileRoute(
  '/_user/releases/new/',
)()

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/_moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const UserReleasesIndexLazyRoute = UserReleasesIndexLazyRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/_user/releases/index.lazy').then((d) => d.Route),
)
const ModeratorModerationIndexLazyRoute =
  ModeratorModerationIndexLazyRouteImport.update({
    id: '/moderation/',
    path: '/moderation/',
    getParentRoute: () => ModeratorRoute,
  } as any).lazy(() =>
    import('./routes/_moderator/moderation/index.lazy').then((d) => d.Route),
  )
const UserRoyaltiesIndexRoute = UserRoyaltiesIndexRouteImport.update({
  id: '/royalties/',
  path: '/royalties/',
  getParentRoute: () => UserRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const UserRoyaltiesReportIdRoute = UserRoyaltiesReportIdRouteImport.update({
  id: '/royalties/$reportId',
  path: '/royalties/$reportId',
  getParentRoute: () => UserRoute,
} as any)
const ModeratorModerationReleaseIdRoute =
  ModeratorModerationReleaseIdRouteImport.update({
    id: '/moderation/$releaseId',
    path: '/moderation/$releaseId',
    getParentRoute: () => ModeratorRoute,
  } as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlatformsRoute = AdminAdminPlatformsRouteImport.update({
  id: '/admin/platforms',
  path: '/admin/platforms',
  getParentRoute: () => AdminRoute,
} as any)
const UserReleasesNewIndexLazyRoute =
  UserReleasesNewIndexLazyRouteImport.update({
    id: '/releases/new/',
    path: '/releases/new/',
    getParentRoute: () => UserRoute,
  } as any).lazy(() =>
    import('./routes/_user/releases/new/index.lazy').then((d) => d.Route),
  )
const UserReleasesReleaseIdIndexRoute =
  UserReleasesReleaseIdIndexRouteImport.update({
    id: '/releases/$releaseId/',
    path: '/releases/$releaseId/',
    getParentRoute: () => UserRoute,
  } as any).lazy(() =>
    import('./routes/_user/releases/$releaseId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/profile': typeof UserProfileRoute
  '/': typeof UserIndexRoute
  '/admin/platforms': typeof AdminAdminPlatformsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/royalties/$reportId': typeof UserRoyaltiesReportIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/royalties': typeof UserRoyaltiesIndexRoute
  '/moderation': typeof ModeratorModerationIndexLazyRoute
  '/releases': typeof UserReleasesIndexLazyRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/releases/$releaseId': typeof UserReleasesReleaseIdIndexRoute
  '/releases/new': typeof UserReleasesNewIndexLazyRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/profile': typeof UserProfileRoute
  '/': typeof UserIndexRoute
  '/admin/platforms': typeof AdminAdminPlatformsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/royalties/$reportId': typeof UserRoyaltiesReportIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/royalties': typeof UserRoyaltiesIndexRoute
  '/moderation': typeof ModeratorModerationIndexLazyRoute
  '/releases': typeof UserReleasesIndexLazyRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/releases/$releaseId': typeof UserReleasesReleaseIdIndexRoute
  '/releases/new': typeof UserReleasesNewIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_moderator': typeof ModeratorRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/': typeof UserIndexRoute
  '/_admin/admin/platforms': typeof AdminAdminPlatformsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_moderator/moderation/$releaseId': typeof ModeratorModerationReleaseIdRoute
  '/_user/royalties/$reportId': typeof UserRoyaltiesReportIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_user/royalties/': typeof UserRoyaltiesIndexRoute
  '/_moderator/moderation/': typeof ModeratorModerationIndexLazyRoute
  '/_user/releases/': typeof UserReleasesIndexLazyRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_user/releases/$releaseId/': typeof UserReleasesReleaseIdIndexRoute
  '/_user/releases/new/': typeof UserReleasesNewIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/profile'
    | '/'
    | '/admin/platforms'
    | '/admin/reports'
    | '/moderation/$releaseId'
    | '/royalties/$reportId'
    | '/admin'
    | '/royalties'
    | '/moderation'
    | '/releases'
    | '/admin/users/$userId'
    | '/admin/users'
    | '/releases/$releaseId'
    | '/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/profile'
    | '/'
    | '/admin/platforms'
    | '/admin/reports'
    | '/moderation/$releaseId'
    | '/royalties/$reportId'
    | '/admin'
    | '/royalties'
    | '/moderation'
    | '/releases'
    | '/admin/users/$userId'
    | '/admin/users'
    | '/releases/$releaseId'
    | '/releases/new'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_moderator'
    | '/_user'
    | '/unauthorized'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_user/profile'
    | '/_user/'
    | '/_admin/admin/platforms'
    | '/_admin/admin/reports'
    | '/_moderator/moderation/$releaseId'
    | '/_user/royalties/$reportId'
    | '/_admin/admin/'
    | '/_user/royalties/'
    | '/_moderator/moderation/'
    | '/_user/releases/'
    | '/_admin/admin/users/$userId'
    | '/_admin/admin/users/'
    | '/_user/releases/$releaseId/'
    | '/_user/releases/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ModeratorRoute: typeof ModeratorRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_moderator': {
      id: '/_moderator'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_user/releases/': {
      id: '/_user/releases/'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof UserReleasesIndexLazyRouteImport
      parentRoute: typeof UserRoute
    }
    '/_moderator/moderation/': {
      id: '/_moderator/moderation/'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModeratorModerationIndexLazyRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_user/royalties/': {
      id: '/_user/royalties/'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof UserRoyaltiesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_user/royalties/$reportId': {
      id: '/_user/royalties/$reportId'
      path: '/royalties/$reportId'
      fullPath: '/royalties/$reportId'
      preLoaderRoute: typeof UserRoyaltiesReportIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/_moderator/moderation/$releaseId': {
      id: '/_moderator/moderation/$releaseId'
      path: '/moderation/$releaseId'
      fullPath: '/moderation/$releaseId'
      preLoaderRoute: typeof ModeratorModerationReleaseIdRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/platforms': {
      id: '/_admin/admin/platforms'
      path: '/admin/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminAdminPlatformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_user/releases/new/': {
      id: '/_user/releases/new/'
      path: '/releases/new'
      fullPath: '/releases/new'
      preLoaderRoute: typeof UserReleasesNewIndexLazyRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/releases/$releaseId/': {
      id: '/_user/releases/$releaseId/'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof UserReleasesReleaseIdIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminPlatformsRoute: typeof AdminAdminPlatformsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminPlatformsRoute: AdminAdminPlatformsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ModeratorRouteChildren {
  ModeratorModerationReleaseIdRoute: typeof ModeratorModerationReleaseIdRoute
  ModeratorModerationIndexLazyRoute: typeof ModeratorModerationIndexLazyRoute
}

const ModeratorRouteChildren: ModeratorRouteChildren = {
  ModeratorModerationReleaseIdRoute: ModeratorModerationReleaseIdRoute,
  ModeratorModerationIndexLazyRoute: ModeratorModerationIndexLazyRoute,
}

const ModeratorRouteWithChildren = ModeratorRoute._addFileChildren(
  ModeratorRouteChildren,
)

interface UserRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
  UserRoyaltiesReportIdRoute: typeof UserRoyaltiesReportIdRoute
  UserRoyaltiesIndexRoute: typeof UserRoyaltiesIndexRoute
  UserReleasesIndexLazyRoute: typeof UserReleasesIndexLazyRoute
  UserReleasesReleaseIdIndexRoute: typeof UserReleasesReleaseIdIndexRoute
  UserReleasesNewIndexLazyRoute: typeof UserReleasesNewIndexLazyRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
  UserRoyaltiesReportIdRoute: UserRoyaltiesReportIdRoute,
  UserRoyaltiesIndexRoute: UserRoyaltiesIndexRoute,
  UserReleasesIndexLazyRoute: UserReleasesIndexLazyRoute,
  UserReleasesReleaseIdIndexRoute: UserReleasesReleaseIdIndexRoute,
  UserReleasesNewIndexLazyRoute: UserReleasesNewIndexLazyRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ModeratorRoute: ModeratorRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
