/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appuserProfileRouteImport } from './routes/(app)/(user)/profile'
import { Route as appadminReportsRouteImport } from './routes/(app)/(admin)/reports'
import { Route as appadminPlatformsRouteImport } from './routes/(app)/(admin)/platforms'
import { Route as appuserRoyaltiesIndexRouteImport } from './routes/(app)/(user)/royalties/index'
import { Route as appadminUsersIndexRouteImport } from './routes/(app)/(admin)/users/index'
import { Route as appuserRoyaltiesReportIdRouteImport } from './routes/(app)/(user)/royalties/$reportId'
import { Route as appmoderatorModerationReleaseIdRouteImport } from './routes/(app)/(moderator)/moderation/$releaseId'
import { Route as appadminUsersUserIdRouteImport } from './routes/(app)/(admin)/users/$userId'

const appuserReleasesIndexLazyRouteImport = createFileRoute(
  '/(app)/(user)/releases/',
)()
const appmoderatorModerationIndexLazyRouteImport = createFileRoute(
  '/(app)/(moderator)/moderation/',
)()
const appuserReleasesNewIndexLazyRouteImport = createFileRoute(
  '/(app)/(user)/releases/new/',
)()
const appuserReleasesReleaseIdIndexLazyRouteImport = createFileRoute(
  '/(app)/(user)/releases/$releaseId/',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appuserProfileRoute = appuserProfileRouteImport.update({
  id: '/(app)/(user)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appadminReportsRoute = appadminReportsRouteImport.update({
  id: '/(app)/(admin)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const appadminPlatformsRoute = appadminPlatformsRouteImport.update({
  id: '/(app)/(admin)/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const appuserReleasesIndexLazyRoute = appuserReleasesIndexLazyRouteImport
  .update({
    id: '/(app)/(user)/releases/',
    path: '/releases/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(user)/releases/index.lazy').then((d) => d.Route),
  )
const appmoderatorModerationIndexLazyRoute =
  appmoderatorModerationIndexLazyRouteImport
    .update({
      id: '/(app)/(moderator)/moderation/',
      path: '/moderation/',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(moderator)/moderation/index.lazy').then(
        (d) => d.Route,
      ),
    )
const appuserRoyaltiesIndexRoute = appuserRoyaltiesIndexRouteImport.update({
  id: '/(app)/(user)/royalties/',
  path: '/royalties/',
  getParentRoute: () => rootRouteImport,
} as any)
const appadminUsersIndexRoute = appadminUsersIndexRouteImport.update({
  id: '/(app)/(admin)/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const appuserRoyaltiesReportIdRoute =
  appuserRoyaltiesReportIdRouteImport.update({
    id: '/(app)/(user)/royalties/$reportId',
    path: '/royalties/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const appmoderatorModerationReleaseIdRoute =
  appmoderatorModerationReleaseIdRouteImport.update({
    id: '/(app)/(moderator)/moderation/$releaseId',
    path: '/moderation/$releaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const appadminUsersUserIdRoute = appadminUsersUserIdRouteImport.update({
  id: '/(app)/(admin)/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const appuserReleasesNewIndexLazyRoute = appuserReleasesNewIndexLazyRouteImport
  .update({
    id: '/(app)/(user)/releases/new/',
    path: '/releases/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(user)/releases/new/index.lazy').then(
      (d) => d.Route,
    ),
  )
const appuserReleasesReleaseIdIndexLazyRoute =
  appuserReleasesReleaseIdIndexLazyRouteImport
    .update({
      id: '/(app)/(user)/releases/$releaseId/',
      path: '/releases/$releaseId/',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(user)/releases/$releaseId/index.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/platforms': typeof appadminPlatformsRoute
  '/reports': typeof appadminReportsRoute
  '/profile': typeof appuserProfileRoute
  '/users/$userId': typeof appadminUsersUserIdRoute
  '/moderation/$releaseId': typeof appmoderatorModerationReleaseIdRoute
  '/royalties/$reportId': typeof appuserRoyaltiesReportIdRoute
  '/users': typeof appadminUsersIndexRoute
  '/royalties': typeof appuserRoyaltiesIndexRoute
  '/moderation': typeof appmoderatorModerationIndexLazyRoute
  '/releases': typeof appuserReleasesIndexLazyRoute
  '/releases/$releaseId': typeof appuserReleasesReleaseIdIndexLazyRoute
  '/releases/new': typeof appuserReleasesNewIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/platforms': typeof appadminPlatformsRoute
  '/reports': typeof appadminReportsRoute
  '/profile': typeof appuserProfileRoute
  '/users/$userId': typeof appadminUsersUserIdRoute
  '/moderation/$releaseId': typeof appmoderatorModerationReleaseIdRoute
  '/royalties/$reportId': typeof appuserRoyaltiesReportIdRoute
  '/users': typeof appadminUsersIndexRoute
  '/royalties': typeof appuserRoyaltiesIndexRoute
  '/moderation': typeof appmoderatorModerationIndexLazyRoute
  '/releases': typeof appuserReleasesIndexLazyRoute
  '/releases/$releaseId': typeof appuserReleasesReleaseIdIndexLazyRoute
  '/releases/new': typeof appuserReleasesNewIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(app)/(admin)/platforms': typeof appadminPlatformsRoute
  '/(app)/(admin)/reports': typeof appadminReportsRoute
  '/(app)/(user)/profile': typeof appuserProfileRoute
  '/(app)/(admin)/users/$userId': typeof appadminUsersUserIdRoute
  '/(app)/(moderator)/moderation/$releaseId': typeof appmoderatorModerationReleaseIdRoute
  '/(app)/(user)/royalties/$reportId': typeof appuserRoyaltiesReportIdRoute
  '/(app)/(admin)/users/': typeof appadminUsersIndexRoute
  '/(app)/(user)/royalties/': typeof appuserRoyaltiesIndexRoute
  '/(app)/(moderator)/moderation/': typeof appmoderatorModerationIndexLazyRoute
  '/(app)/(user)/releases/': typeof appuserReleasesIndexLazyRoute
  '/(app)/(user)/releases/$releaseId/': typeof appuserReleasesReleaseIdIndexLazyRoute
  '/(app)/(user)/releases/new/': typeof appuserReleasesNewIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/platforms'
    | '/reports'
    | '/profile'
    | '/users/$userId'
    | '/moderation/$releaseId'
    | '/royalties/$reportId'
    | '/users'
    | '/royalties'
    | '/moderation'
    | '/releases'
    | '/releases/$releaseId'
    | '/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/platforms'
    | '/reports'
    | '/profile'
    | '/users/$userId'
    | '/moderation/$releaseId'
    | '/royalties/$reportId'
    | '/users'
    | '/royalties'
    | '/moderation'
    | '/releases'
    | '/releases/$releaseId'
    | '/releases/new'
  id:
    | '__root__'
    | '/'
    | '/(app)/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(app)/(admin)/platforms'
    | '/(app)/(admin)/reports'
    | '/(app)/(user)/profile'
    | '/(app)/(admin)/users/$userId'
    | '/(app)/(moderator)/moderation/$releaseId'
    | '/(app)/(user)/royalties/$reportId'
    | '/(app)/(admin)/users/'
    | '/(app)/(user)/royalties/'
    | '/(app)/(moderator)/moderation/'
    | '/(app)/(user)/releases/'
    | '/(app)/(user)/releases/$releaseId/'
    | '/(app)/(user)/releases/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardRoute: typeof appDashboardRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  appadminPlatformsRoute: typeof appadminPlatformsRoute
  appadminReportsRoute: typeof appadminReportsRoute
  appuserProfileRoute: typeof appuserProfileRoute
  appadminUsersUserIdRoute: typeof appadminUsersUserIdRoute
  appmoderatorModerationReleaseIdRoute: typeof appmoderatorModerationReleaseIdRoute
  appuserRoyaltiesReportIdRoute: typeof appuserRoyaltiesReportIdRoute
  appadminUsersIndexRoute: typeof appadminUsersIndexRoute
  appuserRoyaltiesIndexRoute: typeof appuserRoyaltiesIndexRoute
  appmoderatorModerationIndexLazyRoute: typeof appmoderatorModerationIndexLazyRoute
  appuserReleasesIndexLazyRoute: typeof appuserReleasesIndexLazyRoute
  appuserReleasesReleaseIdIndexLazyRoute: typeof appuserReleasesReleaseIdIndexLazyRoute
  appuserReleasesNewIndexLazyRoute: typeof appuserReleasesNewIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/profile': {
      id: '/(app)/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appuserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(admin)/reports': {
      id: '/(app)/(admin)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appadminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(admin)/platforms': {
      id: '/(app)/(admin)/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof appadminPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/releases/': {
      id: '/(app)/(user)/releases/'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof appuserReleasesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(moderator)/moderation/': {
      id: '/(app)/(moderator)/moderation/'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof appmoderatorModerationIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/royalties/': {
      id: '/(app)/(user)/royalties/'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof appuserRoyaltiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(admin)/users/': {
      id: '/(app)/(admin)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appadminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/royalties/$reportId': {
      id: '/(app)/(user)/royalties/$reportId'
      path: '/royalties/$reportId'
      fullPath: '/royalties/$reportId'
      preLoaderRoute: typeof appuserRoyaltiesReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(moderator)/moderation/$releaseId': {
      id: '/(app)/(moderator)/moderation/$releaseId'
      path: '/moderation/$releaseId'
      fullPath: '/moderation/$releaseId'
      preLoaderRoute: typeof appmoderatorModerationReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(admin)/users/$userId': {
      id: '/(app)/(admin)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof appadminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/releases/new/': {
      id: '/(app)/(user)/releases/new/'
      path: '/releases/new'
      fullPath: '/releases/new'
      preLoaderRoute: typeof appuserReleasesNewIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/releases/$releaseId/': {
      id: '/(app)/(user)/releases/$releaseId/'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof appuserReleasesReleaseIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardRoute: appDashboardRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  appadminPlatformsRoute: appadminPlatformsRoute,
  appadminReportsRoute: appadminReportsRoute,
  appuserProfileRoute: appuserProfileRoute,
  appadminUsersUserIdRoute: appadminUsersUserIdRoute,
  appmoderatorModerationReleaseIdRoute: appmoderatorModerationReleaseIdRoute,
  appuserRoyaltiesReportIdRoute: appuserRoyaltiesReportIdRoute,
  appadminUsersIndexRoute: appadminUsersIndexRoute,
  appuserRoyaltiesIndexRoute: appuserRoyaltiesIndexRoute,
  appmoderatorModerationIndexLazyRoute: appmoderatorModerationIndexLazyRoute,
  appuserReleasesIndexLazyRoute: appuserReleasesIndexLazyRoute,
  appuserReleasesReleaseIdIndexLazyRoute:
    appuserReleasesReleaseIdIndexLazyRoute,
  appuserReleasesNewIndexLazyRoute: appuserReleasesNewIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
